variables:
  DEPS: build-essential git

before_script:
 - apt-get -y update
 - apt-get -y build-dep .

build-with-xwayland-bundled-wlroots:
  stage: build
  tags:
    - librem5
  script:
    - apt-get remove libwlroots3 -y
    - git submodule update --init
    - export LC_ALL=C.UTF-8
    - meson . _build -Dxwayland=enabled
    - ninja -C _build
    - ninja -C _build install

build-without-xwayland-bundled-wlroots:
  stage: build
  tags:
    - librem5
  script:
    - apt-get remove libwlroots3 -y
    - git submodule update --init
    - export LC_ALL=C.UTF-8
    - meson . _build -Dxwayland=disabled
    - ninja -C _build
    - ninja -C _build install


build-with-xwayland:
  stage: build
  tags:
    - librem5
  script:
    - export LC_ALL=C.UTF-8
    - meson . _build -Dxwayland=enabled
    - ninja -C _build
    - ninja -C _build install

build-without-xwayland:
  stage: build
  tags:
    - librem5
  script:
    - export LC_ALL=C.UTF-8
    - meson . _build -Dxwayland=disabled
    - ninja -C _build
    - ninja -C _build install

